[package]
name = "monch_util_ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.47"
clap = "3.0.0-beta.5"
monch_io = { path = "../monch_io" }
serde = "1"
