[package]
name = "monch_syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.30"

[dev-dependencies]
insta = { version = "1.8.0", features = ["glob"] }
